blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name="home"),   #as_view porque estamos trabajado con una clase

    path('blog/', include('blog.urls', namespace='blog')),

    path('entries/', include('posts.urls', namespace='entries')),
]

posts/urls.py
from django.urls import path
from posts.views import (
    dummy_view,
    status_code_view,
    entry_list,
    redirect_back_home,
    MyClassView,
    MyListView
    )

app_name = 'posts'

urlpatterns = [
    path('', MyListView.as_view(), name='entry_list'),
    path('<id>/', dummy_view, name='entry_detail'),
    #path('(?P<id>[0-9]{4})/(?P<slug>[\w-]+)/$', dummy_view, name='entry_detail')   #url con expresiones regulares
    path('<id>/delete', dummy_view, name='entry_delete'),
    path('<id>/update', dummy_view, name='entry_update')
]

blog/models.py
from django.db import models

class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title

posts/models.py
from django.db import models
from django.shortcuts import redirect
from django.urls import reverse

class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    authors = models.ManyToManyField(Author, related_name='entries')
    n_comments = models.IntegerField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return redirect(reverse("entries:entry-detail", kwargs={   
            "id": self.id
            })) 
    

users/models.py
import datetime
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    cars = models.ManyToManyField('Car', verbose_name="user's car")


STATUS_CHOICES = (
    ('R', 'Reviewed'),
    ('N', 'Not Reviewed'),
    ('E', 'Error'),
    ('A', 'Accepted')
)

class Website(models.Model):
    name = models.CharField(max_length=30)
    url = models.URLField()
    release_date = models.DateField()
    rating = models.IntegerField()
    status = models.CharField(choices=STATUS_CHOICES, max_length=1)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)   #si se borra el usuario, se borra el sitio web

    class Meta:
        ordering = ['rating']
        #db_table = 'website_custom_table_name'
        verbose_name = 'The Website'
        verbose_name_plural = 'The Websites'

    def was_released_last_week(self):
        if self.release_date < datetime.date(2022,7,6):
            return "Released before last week"
        else:
            return "Released this week"

    @property
    def get_full_name(self):
        return f"This is the complete name of the website: {self.name}"

    def __srt__(self):
        return self.name

    def get_absolute_url(self):
        return f"/websites/{self.id}"
    
    def save(self, *args, **kwargs):
        print("Estamos guardando")
        super().save(*args, **kwargs)



class Car(models.Model):
    name = models.CharField(max_length=40, primary_key=True)

blog/forms.py
from django import forms
from .models import Post

#creación de un formulario para crear post desde la app usando el modelo Post
class PostCreateForm(forms.ModelForm):   
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts=Post.objects.all()
        context={
            'posts':posts
        }
        return render(request, 'blog/blog_list.html', context)


class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog/blog_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            form=PostCreateForm(request.POST)
            if form.is_valid():
                title= form.cleaned_data.get('title')
                content= form.cleaned_data.get('content')

                p, created= Post.objects.get_or_create(title=title,content=content) #la info que queremos guardar en la tabla post deriva del formulario 
                p.save()
                return redirect('blog:home')
        context={

        }
        return render(request, 'blog/blog_create.html', context)


class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context={
            'post':post
        }
        return render(request, 'blog/blog_detail.html', context)


class BlogUpdateView(UpdateView):    #editar una vista
    model=Post
    fields=['title','content']
    template_name='blog/blog_update.html'   

    def get_success_url(self):
        pk= self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})


class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog/blog_delete.html'
    success_url=reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request, 'core/home.html', context)

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView
from .models import Blog, Entry

def dummy_view(request):
    return render(request, "posts/post_list.html", {})


def status_code_view(request):
    return render(request, "posts/post_list.html", {})

def entry_list(request):
    return render(request, "posts/post_list.html", {})

def redirect_back_home(request):
    return redirect('entries:entry_detail', id=1)

class MyClassView(View):
    def get(self, request):
        print("corremos codigo")
        return HttpResponse("Response basado en clases")

class MyListView(ListView):
    model = Entry

templates/blog/blog_create.html
{% extends 'core/base.html' %}

{% block title %}Create New Post {% endblock %}

{% block content %}
<section class="section-container">
    <h1>Create New Post!</h1>

    {% if request.user.is_authenticated %}
    
    <form method="POST" class="form-container">
        {% csrf_token %}
        <div class="form-section">
            <label for="id_title">Title:</label><br>
            <input type="text" id="id_title" name="title">
        </div>
        <div class="form-section">
            <label for="id_content">Content:</label><br>
            <textarea type="text" id="id_content" name="content"></textarea>
        </div>
        <button type="submit" id="button-form">SUBMIT</button>
    </form>

    {% else %}
    <div style="color: white;">
        <p>Debe registrarse primero</p>
        <a href="#">Registrarse</a>
        <a href="#">Ingresar</a>
    </div>
    {% endif %}

</section>
{% endblock %}

templates/blog/blog_delete.html
{% extends 'core/base.html' %}

{% block title %}Delete Post{% endblock %}

{% block content %}

<section class="section-container section-delete">
    <h1>Are you sure you want to delete this post?</h1>

    <form method="POST" class="delete-container">
        {% csrf_token %}
        {{form}}
        <button type="submit" id="button-delete">Delete</button>
        <a href="{% url 'blog:home' %}"><button type="button" id="button-no">No</button></a>
    </form>
</section>

{% endblock %}

templates/blog/blog_detail.html
{% extends 'core/base.html' %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}

<section class="section-container">
    <h1>{{post.title}}</h1>

    <div class="form-container">
        <p>{{post.content|safe}}</p>
    </div>
</section>

{% endblock %}

templates/blog/blog_list.html
{% extends 'core/base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}

<section class="posts">
    <h1>Posts</h1>

    <div class="post-container">
        {% for post in posts %}
        <div class="post-item">
            <div>
                <a href="{% url 'blog:detail' post.id %}"><h1> {{post.title}}</h1></a>
                <p>{{post.content|striptags|truncatechars:200}}</p>
            </div>
            <div>
                <button class="button-list"><a href="{% url 'blog:update' post.id %}">Update</a></button>
                <button class="button-list"><a href="{% url 'blog:delete' post.id %}">Delete</a></button>
            </div>
        </div>
        {% endfor %}
    </div>

</section>

{% endblock %}

templates/blog/blog_update.html
{% extends 'core/base.html' %}

{% block title %}Update Post{% endblock %}

{% block content %}

<section class="section-container">
    <h1>Update Post!</h1>

    <form method="POST" class="form-container">
        {% csrf_token %}
        <div class="form-section">
            Title:<br>
            {{form.title}}
            <br>
            Content:<br>
            {{form.content}}<br>
        </div>
        <button type="submit" id="button-form">Update</button>
    </form>
</section>

{% endblock %}

templates/core/base.html
{% load static %}
{% load tailwind_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="{% static 'css/core/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/blog/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/core/normalize.css' %}" rel="stylesheet">

    {% tailwind_css %}

    <title>{% block title %} {% endblock %}</title>
</head>
<body class="body-container">
    <header>
        {% include 'core/partials/_navbar.html' %}
    </header>
    <main>
        {% block content %}

        {% endblock %}
    </main>
    <footer>
        {% include 'core/partials/_footer.html' %}
    </footer>
</body>
</html>

templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="home-container">
    <h1 class="titulo">Hello, visit my blog!</h1>
</section>
{% endblock content %}

templates/core/partials/_footer.html
<section class="footer-container">
    <div>
        <p>Victoria Cia</p>
    </div>
    <div>
        Thanks for visit!
    </div>
</section>

templates/core/partials/_navbar.html
<nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex items-center justify-between h-16">
            <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-center">
                <!--
                <div class="flex-shrink-0 flex items-center">
                    <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-500-mark-white-text.svg" alt="Workflow">
                </div>
                -->
                <div class="block sm:block sm:ml-6">
                    <div class="flex space-x-4 justify-center">
                        <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                        <a href="{% url 'home' %}" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Home</a>
            
                        <a href="{% url 'blog:home' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Blog</a>

                        <a href="{% url 'blog:create' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">+ New Post</a>

                        <a href="{% url 'posts:entry_list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Blog 2.0</a>

                    </div>
                </div>
            </div>         
        </div>
    </div>
</nav>

templates/posts/entry_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/posts/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Pagina web de victoria</h1>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>